# Generated by Django 4.1 on 2025-10-20 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("karakuchi_room", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["id"],
                "verbose_name": "ユーザー",
                "verbose_name_plural": "ユーザー一覧",
            },
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="タイトル")),
                ("description", models.TextField(blank=True, verbose_name="詳細")),
                (
                    "start_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="投票開始日時"
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="投票終了日時"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="公開フラグ"),
                ),
                (
                    "is_open",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "受付中"), (1, "受付終了")],
                        default=0,
                        verbose_name="投票フラグ",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="削除フラグ"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="surveys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "アンケート",
                "verbose_name_plural": "アンケート一覧",
                "db_table": "surveys",
            },
        ),
        migrations.AddIndex(
            model_name="survey",
            index=models.Index(
                fields=["user", "-created_at"], name="surveys_user_id_e3e1d4_idx"
            ),
        ),
    ]
