# Generated by Django 5.0 on 2025-10-31 10:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("karakuchi_room", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="email_address",
            new_name="email",
        ),
    ]
