# Generated by Django 5.0 on 2025-10-31 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karakuchi_room', '0002_rename_email_address_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
