# Generated by Django 4.1 on 2025-10-20 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karakuchi_room', '0003_tag_tagsurvey_tag_tags_tag_nam_c3b10a_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='選択項目')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('survey', models.ForeignKey(db_column='survey_id', on_delete=django.db.models.deletion.PROTECT, related_name='options', to='karakuchi_room.survey', verbose_name='アンケートID')),
            ],
            options={
                'verbose_name': '選択肢',
                'verbose_name_plural': '選択肢一覧',
                'db_table': 'options',
            },
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['survey'], name='options_survey__37ad10_idx'),
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['is_deleted'], name='options_is_dele_d114cf_idx'),
        ),
    ]
