# Generated by Django 4.1 on 2025-10-20 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("karakuchi_room", "0004_option_option_options_survey__37ad10_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="コメント"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="削除フラグ"),
                ),
                (
                    "option",
                    models.ForeignKey(
                        db_column="option_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="votes",
                        to="karakuchi_room.option",
                        verbose_name="選択ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="votes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザーID",
                    ),
                ),
            ],
            options={
                "verbose_name": "投票",
                "verbose_name_plural": "投票一覧",
                "db_table": "votes",
            },
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(fields=["user"], name="votes_user_id_72a822_idx"),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(fields=["option"], name="votes_option__7be548_idx"),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(fields=["is_deleted"], name="votes_is_dele_7af120_idx"),
        ),
    ]
