# Generated by Django 4.1 on 2025-10-21 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("karakuchi_room", "0005_vote_vote_votes_user_id_72a822_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="survey",
            field=models.ForeignKey(
                db_column="survey_id",
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="votes",
                to="karakuchi_room.survey",
                verbose_name="アンケートID",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.UniqueConstraint(
                fields=("user", "survey", "is_deleted"),
                name="uq_vote_user_survey_active",
            ),
        ),
    ]
