# Generated by Django 5.0 on 2025-11-12 09:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("karakuchi_room", "0005_survey_tag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="survey",
            old_name="tag",
            new_name="tag_survey",
        ),
    ]
